# Get all books.
GET https://cse341-project2-a570.onrender.com/books/


# Get book by ID.
GET https://cse341-project2-a570.onrender.com/books/668088670b756ba4f239a236


### create book
POST https://cse341-project2-a570.onrender.com/books/ HTTP/1.1 content-type: application/json

{
  "title": "any",
  "author": "any",
  "publicationYear": "1999"
}



# Update book information.
PUT https://cse341-project2-a570.onrender.com/books/66809c741b20113167cb5c8a HTTP/1.1 content-type: application/json

{
    "title": "My New Favorite Book",
    "author": "My New Favorite Author",
    "publicationYear": "2013"
}


# Delete a book.
DELETE https://cse341-project2-a570.onrender.com/books/66916d8a359ee91522ea00aa HTTP/1.1